name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

      - name: Start Application
        run: npm start &
      
      - name: Run Cypress Tests
        run: npm run cypress:run
